#define IDD_MISSION 46
#define IDD_BUILD_PERMS_MENU 4118

#define IDC_PERM_CLOSE_BUTTON 650
#define IDC_PERM_CONTROL_GRP 9869

#define COLOR_AUTHORIZED [0,0.9,0,1]
#define COLOR_DENIED [0.9,0,0,1]
#define COLOR_BACKGROUND [0.75,1,0.75,0.12]
#define FONT_SIZE (0.020 * safezoneH)

#define INF_VEH_PERM 0
#define TRANSPORT_VEH_PERM 1
#define COMBAT_VEH_PERM 2
#define AERIAL_PERM 3
#define DEFENCES_PERM 4
#define DECORATIVE_PERM 5
#define SUPPORT_PERM 6
#define RECYCLE_PERM 7